CREATE TABLE `chemical_data` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Li` float DEFAULT NULL,
  `B` float DEFAULT NULL,
  `N` float DEFAULT NULL,
  `Na` float DEFAULT NULL,
  `P` float DEFAULT NULL,
  `Cl` float DEFAULT NULL,
  `C` float DEFAULT NULL,
  `Al` float DEFAULT NULL,
  `Si` float DEFAULT NULL,
  `K` float DEFAULT NULL,
  `Ca` float DEFAULT NULL,
  `V` float DEFAULT NULL,
  `Cr` float DEFAULT NULL,
  `Fe` float DEFAULT NULL,
  `Mn` float DEFAULT NULL,
  `cobalt` float DEFAULT NULL,
  `Ni` float DEFAULT NULL,
  `Cu` float DEFAULT NULL,
  `Zn` float DEFAULT NULL,
  `Mg` float DEFAULT NULL,
  `As` float DEFAULT NULL,
  `Se` float DEFAULT NULL,
  `Br` float DEFAULT NULL,
  `Sr` float DEFAULT NULL,
  `Mo` float DEFAULT NULL,
  `Ag` float DEFAULT NULL,
  `Cd` float DEFAULT NULL,
  `In` float DEFAULT NULL,
  `Ba` float DEFAULT NULL,
  `La` float DEFAULT NULL,
  `Ti` float DEFAULT NULL,
  `Pb` float DEFAULT NULL,
  `Bi` float DEFAULT NULL,
  `U` float DEFAULT NULL,
  `CH4` float DEFAULT NULL,
  `H2S` float DEFAULT NULL,
  `H2` float DEFAULT NULL,
  `CO` float DEFAULT NULL,
  `nitrate` float DEFAULT NULL,
  `nitrite` float DEFAULT NULL,
  `ammonium` float DEFAULT NULL,
  `sulfate` float DEFAULT NULL,
  `chloride` float DEFAULT NULL,
  `phosphate` float DEFAULT NULL,
  `iron2` float DEFAULT NULL,
  `bicarbonate` float DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `location` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `feature_name` varchar(60) DEFAULT NULL,
  `lat` double DEFAULT NULL,
  `lng` double DEFAULT NULL,
  `feature_system` varchar(50) DEFAULT NULL,
  `description` varchar(200) DEFAULT NULL,
  `toilet` tinyint(1) DEFAULT NULL,
  `parkbench` tinyint(1) DEFAULT NULL,
  `track` tinyint(1) DEFAULT NULL,
  `private` tinyint(1) DEFAULT NULL,
  `colour` varchar(50) DEFAULT NULL,
  `access` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `feature_name` (`feature_name`)
) ;

CREATE TABLE `physical_data` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `initialTemp` double DEFAULT NULL,
  `pH` double DEFAULT NULL,
  `redox` double DEFAULT NULL,
  `dO` double DEFAULT NULL,
  `conductivity` double DEFAULT NULL,
  `size` varchar(20) DEFAULT NULL,
  `colour` varchar(7) DEFAULT NULL,
  `ebullition` varchar(50) DEFAULT NULL,
  `turbidity` double DEFAULT NULL,
  `dnaVolume` double DEFAULT NULL,
  `ferrousIronAbs` double DEFAULT NULL,
  `sampleTemp` double DEFAULT NULL,
  `soilCollected` tinyint(1) DEFAULT NULL,
  `waterColumnCollected` tinyint(1) DEFAULT NULL,
  `gasVolume` double DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `sample` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sample_number` varchar(10) NOT NULL,
  `date_gathered` datetime NOT NULL,
  `location_id` int(11) DEFAULT NULL,
  `phys_id` int(11) DEFAULT NULL,
  `sampler` varchar(50) NOT NULL,
  `chem_id` int(11) DEFAULT NULL,
  `comments` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_SAMPLE_location` (`location_id`),
  KEY `FK_SAMPLE_phys` (`phys_id`),
  KEY `FK_SAMPLE_chem` (`chem_id`),
  CONSTRAINT `FK_SAMPLE_chem` FOREIGN KEY (`chem_id`) REFERENCES `chemical_data` (`id`),
  CONSTRAINT `FK_SAMPLE_location` FOREIGN KEY (`location_id`) REFERENCES `location` (`id`),
  CONSTRAINT `FK_SAMPLE_phys` FOREIGN KEY (`phys_id`) REFERENCES `physical_data` (`id`)
  UNIQUE KEY `sample_number` (`sample_number`)
);

CREATE TABLE `taxonomy` (
  `sample_id` int(11) NOT NULL,
  `id` int(11) NOT NULL,
  `taxName` varchar(50) NOT NULL,
  `otuNum` int(11) NOT NULL,
  `otuPer` double NOT NULL,
  `total` int(11) NOT NULL,
  `totalPer` int(11) NOT NULL,
  `sequence` text,
  `seqLen` int(11) DEFAULT NULL,
  `phylum` varchar(50) DEFAULT NULL,
  `phylum_Confidence` double DEFAULT NULL,
  `class` varchar(50) DEFAULT NULL,
  `class_Confidence` double DEFAULT NULL,
  `order` varchar(50) DEFAULT NULL,
  `order_Confidence` double DEFAULT NULL,
  `family` varchar(50) DEFAULT NULL,
  `family_Confidence` double DEFAULT NULL,
  `Genus` varchar(50) DEFAULT NULL,
  `genus_Confidence` double DEFAULT NULL,
  `species` varchar(50) DEFAULT NULL,
  `species_Confidence` double DEFAULT NULL,
  PRIMARY KEY (`sample_id`,`id`),
  UNIQUE KEY `taxName` (`taxName`),
  CONSTRAINT `FK_taxonomy_sample` FOREIGN KEY (`sample_id`) REFERENCES `sample` (`id`)
);

CREATE TABLE `image` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sample_id` int(11) NOT NULL,
  `image_path` varchar(150) NOT NULL,
  `image_type` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`,`sample_id`),
  KEY `FK_images_samples` (`sample_id`),
  CONSTRAINT `FK_images_samples` FOREIGN KEY (`sample_id`) REFERENCES `sample` (`id`)
);
